repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint app tests
        pass_filenames: false
        language: system